apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echoline.fullname" . }}
  labels:
    app: echoline
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echoline
  template:
    metadata:
      labels:
        app: echoline
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: HTTP_ADDR
              value: {{ .Values.env.HTTP_ADDR | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: echoline-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: echoline-secrets
                  key: jwt-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
